### ISSUE TITLE
The information from devices column in traveler instance list is shown by tags on the traveler instance tags. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#121]

**Comment by iTerminate** [comment]
![image002](https://user-images.githubusercontent.com/13026379/51612256-b33de480-1ee6-11e9-8cac-8bf2098b4720.jpg)
![image004](https://user-images.githubusercontent.com/13026379/51612260-b5a03e80-1ee6-11e9-9ccc-7ff29fc034b3.jpg)

**Comment by shengb** [comment]
@iTerminate More straightforward details? I did not see "APSU-EMI Cabinet [Unit: 37]" and "[QRID: 2318]" in picture 1, which are shown as tags in 2nd picture.

**Comment by dongliu** [comment]
will fix this.
