### ISSUE TITLE
How do you rename a template? 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#13]

**Comment by shengb** [comment]
Currently, the renaming could be done in the template config.
It would be nice to have an edit button near the title when editing a template.

**Comment by dongliu** [comment]
The experience of template is the same as travelers now. go to the config page via the gear icon, and then make the changes. 
<img width="539" alt="screen shot 2018-09-07 at 8 57 17 pm" src="https://user-images.githubusercontent.com/599397/45250070-c9a12600-b2e0-11e8-989a-7a5204082c75.png">

**Comment by shengb** [comment]
Exactly. This is available from the config page via the gear icon.
What I was talking exactly was in the edit page via the edit icon.

We can treat that as a work around, and put this need on hold for now since we have this work around.
