### ISSUE TITLE
Radio button input values not updated properly. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#14]
![image](https://user-images.githubusercontent.com/13026379/45223224-4bab3380-b27c-11e8-9f41-706f4407d9ac.png)

It seems that it only looks at the last input radio button value I added. If I specify radio 0 value and add and specify radio 1 value and add next one and so on it works. However when I add four inputs first and then edit them as needed only the last one gets updated. 

It does seem to work when I edit an existing radio button set, all the radio buttons present get updated as expected. However as soon as I add a new button, the last one is the only that gets updated.

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/22/commits/f183c7a4f9dc4b1e9d8884991e07a3e3e35ae6ff
