### ISSUE TITLE
When I add multiple radio button inputs and remove one, all dissappear. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#15]
![image](https://user-images.githubusercontent.com/13026379/45223587-45698700-b27d-11e8-8537-4798791e9162.png)

Clicking done after the state as shown in screen shot, the edit button no longer works on the input. 

It seems that it has something to do with the input value matching. When I change one input that one would stay.  I think it should be possible during editing that input radio button values may match as users add and remove inputs.

**Comment by dongliu** [comment]
reproduced, fixing

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/22
