### ISSUE TITLE
Hiding reporting ID from column header in discrepancy table view

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#171]

**Comment by dongliu** [comment]
@shengb not sure what the reporting id refer to. please explain better to have a screenshot.

**Comment by shengb** [comment]
Hide those as circled in the screenshot as below:
![Screen Shot 2019-05-13 at 8 31 24 AM](https://user-images.githubusercontent.com/3741779/57625631-dd7ce600-7559-11e9-82c1-6e360c562ee4.png)
