### ISSUE TITLE
A better way in API when returning discrepancy data

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#175]
Shall we return more meta data info in discrepancy API when returning history log?
I am thinking to return real name for each record instead of its UID, and its "reporting ID".
Or there are some better approach?

```
[
 ... 
 {
    "_id": "5cd978977c29f7001481c643",
    "referenceForm": "5ccb1492d3f68b0013084713",
    "records": [
      {
        "_id": "5cd978a97c29f7001481c647",
        "name": "7bc18d6b",
        "value": "Test 2"
      },
      {
        "_id": "5cd978a97c29f7001481c646",
        "name": "1957cddd",
        "value": "NDA"
      },
      {
        "_id": "5cd978a97c29f7001481c645",
        "name": "cde98500",
        "value": "Return to Supplier"
      },
      {
        "_id": "5cd978a97c29f7001481c644",
        "name": "c8e27565",
        "value": "Demo Test"
      }
    ],
    "inputBy": "guobao",
    "inputOn": "2019-05-13T14:01:13.388Z"
  }
]
```

**Comment by dongliu** [comment]
This is related to https://github.com/AdvancedPhotonSource/traveler/issues/174

We need the context of traveler and discrepancy form for the usage of the discrepancy data. 

We can also create a more limited endpoint to generate a representation based on *current* active discrepancy form with label and value. 

The client (we see how it works on web page, the same for other client) should be able to create any representation based on the form and the data.
