### ISSUE TITLE
Step numbers and updating existing form. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#192]
It seems that I need to hit edit and done for each existing step before I get step numbers assigned whenever I edit existing forms created before step number feature. 

Some potential solutions:

1. Automatically auto-generate step numbers for existing forms as soon as save button is hit with the new editor. 
2. When a form without step numbers is opened in edit, auto assign step numbers so that when it is saved the numbers are now a part of the form. 

@shengb what do you think?

**Comment by shengb** [comment]
It is heavy for an existing form. We have to go every step to get it assign a new step number.
The 2 solutions need a knowledge whether a form has step number assigned or not.
Maybe we can have one button "(re)generate steps" or something like that in the form design UI, and let user to click that button?

@iTerminate any better solution?
@dongliu Any comment?

**Comment by dongliu** [comment]
I thought about this before implemented the numbering feature in form builder.A button to `generate numbering` is the most straightforward user experience that I can think. 
- we should not force an old form to have numbering if it works well for the user
- the button click will do nothing for a form that already have numbering

I am starting to work on this.
