### ISSUE TITLE
Numbering feature implemented does not fulfill requirements

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#202]
Instead of numbering each input the numbering functionality should: 
- Number each rich instruction
- Reset the number per section
  - EX:

# Section One
1. rich instruction
- [ ] some check
2. another instruction
- [ ] another check
# Section Two
1. some instructions
- [ ] section 2 check
2. more instructions 
- [ ] some other check

**Comment by shengb** [comment]
After discussing, decision is made to add a styling to the numbers to differentiate the step numbers and user data.
