### ISSUE TITLE
No two RELEASED templates may have the same name and revision ID

### ISSUE THREAD

**Issue by dongliu** [AdvancedPhotonSource/traveler#233]
- [ ] A mechanism is needed to show templates with latest revision ID, and all RELEASED templates. By default, it shows latest revision ID only

**Comment by dongliu** [comment]
For normal and discrepancy templates, it is straightforward to use the version number to tell which is the latest released version. 
What about normal_discrepancy type? There are two version numbers, like `n:m`, `n` for the normal part, and 'm' for the discrepancy part.
I assume we will first check the `n` part, if `n` is the same for two version, then check the `m` part.

**Comment by shengb** [comment]
That mechanism is good enough. It seems that there is a bug in `n:m` numbering.

**Comment by dongliu** [comment]
@shengb  for `By default, it shows latest revision ID only`, 
does it mean: 

1. for a given released templated name, at any time, there is only one version (the highest version)
2. a new traveler can only initiated from the current (highest version) template
3. when a template is archived/obsoleted, all the versions (highest and older) are in archived status

**Comment by shengb** [comment]
A1: Originally, yes. As of now, I think we should adopt an administrative approach. We can have more than one version released, and leave it to the eTraveler admin to decide whether the other early released templates shall be archived. Once we get feedback from the user, we can discuss this again, and address this there.

A2: See above. As the first approach, let's do it in a system administrative approach. It means that for now, there will be more than one revision released for a particular template, and user can instance a traveler from any of those released templates.

A3: I am not sure what the mean exactly. You mean a template in DRAFT status? For a released template, it is all by itself. Operation on one shall not affect the other released templates although there are some logic connections. Marking one archived/obsoleted shall not impact the others unless there are some use cases which I am not aware of.
