### ISSUE TITLE
Merge archived and archived released templates into one.

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#249]
The status column provides redundant information currently as it shows 'archived'. We can re-purpose it for draft / released.

**Comment by dongliu** [comment]
The two tables could be merged to one table. However, I think that will mislead the user to think draft forms and released forms are the same. They are saved in different collections, and they have different types. An achieved draft form will only be viewable by those who have access, but an archived released form is viewable by everyone.  When a released form is cloned, only the base form will be cloned into the new form.

**Comment by shengb** [comment]
They might have same name, but definitely with different status as well as different version number.
Not sure what it means exactly "have different types". 
"An achieved draft form will only be viewable by those who have access, but an archived released form is viewable by everyone." That's a good point.

**Comment by dongliu** [comment]
draft form: normal, discrepancy 
released form: normal, discrepancy, and normal with discrepancy

**Comment by shengb** [comment]
Good point. It seems another column to differentiate them.
