### ISSUE TITLE
Add Traveler instance into binder results in 400 error

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#27]
It reported as HTTP request failed, and the log shows POST 400 error. 
I am using Firefox 60.1.0esr (64-bit).
Attached is a demo for this error.
[Adding_Traveler_2_Binder.m4v.zip](https://github.com/AdvancedPhotonSource/traveler/files/2368445/Adding_Traveler_2_Binder.m4v.zip)

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/29

**Comment by shengb** [comment]
Double check with firefox, and verified the fix.
