### ISSUE TITLE
Submission with unfinished required fields

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#32]
When working a traveler, if there is any required field not complete, the validation shows it as red, which is desired. 
However, a user can submit uncompleted traveler silently without any warning/notification. When an approver checks the validation, it shows all unfinished "required" field in green, which would mislead the approver that everything has been finished.

As a minimum, if there is any unfinished mandatory field, a warning should be given to all the parties who submits it, and approves it.

**Comment by shengb** [comment]
after jobs submitted for completion, it always passes the validation no matter the required field is filled up or not.

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/39
