### ISSUE TITLE
Sharing function does not work

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#46]
All buttons, "Add to share"/Modify/Remove, are deactivated.

**Comment by shengb** [comment]
This "Add to share button" is greyed out after adding an user.

**Comment by shengb** [comment]
Saving results the following errors:

web_1  | /app/lib/share.js:35
web_1  |     var id = result[0].sAMAccountName.toLowerCase();
web_1  |                                       ^
web_1  |
web_1  | TypeError: Cannot read property 'toLowerCase' of undefined
web_1  |     at /app/lib/share.js:35:39
web_1  |     at mapDefaultKeyNames (/app/lib/ldap-client.js:67:12)
web_1  |     at EventEmitter.<anonymous> (/app/lib/ldap-client.js:52:21)
web_1  |     at emitOne (events.js:116:13)
web_1  |     at EventEmitter.emit (events.js:211:7)
web_1  |     at sendResult (/app/node_modules/ldapjs/lib/client/client.js:1389:22)
web_1  |     at messageCallback (/app/node_modules/ldapjs/lib/client/client.js:1421:16)
web_1  |     at Parser.onMessage (/app/node_modules/ldapjs/lib/client/client.js:1089:14)
web_1  |     at emitOne (events.js:116:13)
web_1  |     at Parser.emit (events.js:211:7)
web_1  |     at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:117:8)
web_1  |     at Socket.onData (/app/node_modules/ldapjs/lib/client/client.js:1076:22)
web_1  |     at emitOne (events.js:116:13)
web_1  |     at Socket.emit (events.js:211:7)
web_1  |     at addChunk (_stream_readable.js:263:12)
web_1  |     at readableAddChunk (_stream_readable.js:250:11)

**Comment by shengb** [comment]
This error causes client crash, and user has to login again.

**Comment by dongliu** [comment]
please check if https://github.com/AdvancedPhotonSource/traveler/pull/55/files fix the above issue. 

The `sAMAccountName` is a AD specific thing.  changed to `uid`, this will work for at least the AD in docker. However, because of an AD instance can be different in operation, the attribute name should go to a configuration file. Then it can be adjusted according to the operation environment.

**Comment by shengb** [comment]
That would be nice to have the auto complete list. An interesting thread on sAMAccountName/uid or userPrincipalName: https://serverfault.com/questions/567776/which-field-to-use-when-authenticating-against-active-directory

Going with a configuration file would be a good approach, which could be done later. 
Close this topic for now.

**Comment by dongliu** [comment]
if the auth (login) works, then this should work similarly as the auth part. We now has a hard coded key in the program, which should be a parameter from a config file likely in the `ad.json`. I do not know how the APS AD is configured. The `mapDefaultKeyNames` converts a search result, we can use it to convert the search as well.
