### ISSUE TITLE
Notify user that a duplicate key was entered. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#5]
I see that it fails the save and shows in log file duplicate input userkey however the user just sees HTTP request fail. 

It would be nice if it would show the input key that is duplicate in the form on instead of HTTP request fail and or if it would also notify the user when they are about to click done on an input using an existing key.

**Comment by shengb** [comment]
The error message needs to be more specific and detailed, to help the user a lot instead of a generic http request fail.

**Comment by dongliu** [comment]
ready in https://github.com/AdvancedPhotonSource/traveler/pull/8
