### ISSUE TITLE
Example of Table Report

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#57]
Here is an example what a report may look like:
![screen shot 2018-09-24 at 1 14 15 pm](https://user-images.githubusercontent.com/3741779/45970443-22203500-bffc-11e8-9d9f-7a2323834c9e.png)

**Comment by dongliu** [comment]
@shengb do you mean that we create a form that has the list of keys, and then generate a table report like the example?

**Comment by shengb** [comment]
One example: User is doing a measurement for a device for example magnet, or vacuum. He might or might not create a binder for the work. It will be useful to generate a summary report to show the user how many devices have been measured, and what's the value.

**Comment by dongliu** [comment]
I am working on selecting a set of travelers and generate report from them. Several design decisions to make: 

1. do we allow a report to contain travelers from different forms/templates? I assume the answer is yes

2. should we display all the keys that are included in all the forms in a report? I assume this is at least an option

3. should we allow the user to choose a subset of keys out of all to display in the report? that is, the user can control the format of a report. Such a control should also include the list of travelers the user has chosen. 

4. if yes for 3, then how can the user `save` such a report control, use it later, or share it with others?  if not just print it out, and then throw it away. 

I know some of these questions might be out of the scope of this project, but I want to have a design with all these aspects considered.

**Comment by shengb** [comment]
1. Yes;
2. Right, it could be an option, maybe we should include the keys in a report. It raises another question how to name a column properly. Maybe we have 3 options available: a) use the keys as column names; b) have it configurable; and c) mapping it when adding a new key. I would say we go with approach a) as of now;
3. My first answer is yes, unless there is an implementation difficulty. 
4. Good question. As of now, we do not save the search results as the reporting might change with time. This goes back to question 2). Maybe we do need to include all seaching keys & tags in the report.
