### ISSUE TITLE
API to retrieve data

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#61]
When I am trying to get data from traveler with curl, for example:
curl --insecure -u username:password https://localhost:3001/apis/travelers/

It results:
Cannot GET /apis/travelers/
and the server reported a 404 error.

I am using the docker with right username/password, and started the image with the docker-compose

**Comment by shengb** [comment]
This was my first try to verify the improved API function on tags & keys, "User-entered data can then be retrieved via the keys" & "Improve API to search and return all keys & tags".

**Comment by dongliu** [comment]
the traveler key search is added in https://github.com/AdvancedPhotonSource/traveler/pull/62

an example url is `https://localhost:3443/apis/travelers/?userkey=phone`
the api can search traveler by tag, device, and userkey
search form by tag and userkey
The api cred is in `docker/api.json`

**Comment by shengb** [comment]
It results:
$ curl --insecure https://guobao:password@localhost:3443/apis/travelers/
Unauthorized

The server reports:
web_1  | GET /apis/travelers/ 401 1ms - 1
