### ISSUE TITLE
Report for travelers data within one binder

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#67]
There are a few issues.
For one binder:
1. User cannot select tags;
2. User cannot select keys;
3. after selected a couple travelers, "Generate report" results in error "Cannot POST /travelers/report/"

For travelers:
1. after selected a couple travelers, "Generate report" results in error "Cannot POST /travelers/report/"

**Comment by dongliu** [comment]
You need to restart your traveler container after pulling in the changes. 

I will add the tags and devices filter to the binder view. Do we also need the keys column there?

**Comment by shengb** [comment]
Yes, I just figured that out. After restarting the server, here are the problem for travelers:
1. the report includes all keys, instead of selected keys;
2. the "Copy" & pull-down of "Save" are blacked out:
![screen shot 2018-10-02 at 9 43 46 am](https://user-images.githubusercontent.com/3741779/46356147-bfe0b900-c627-11e8-934c-ae84424c8231.png)

**Comment by shengb** [comment]
For binders, yes, we need the keys column there, therefore enable user to be able to choose which data field to report.

**Comment by dongliu** [comment]
When you click on the black part, the browser will promote you to enable flash. after that, you should be able to do the operations. 

I am working on the tool the configure the showed columns/keys in the report.

**Comment by shengb** [comment]
Good. I happened to find that either. It behaviors better in Chrome.

**Comment by shengb** [comment]
Summary for the reporting need:
When no key is selected, report summary with traveler status as of now.

When keys are selected, report summary report  + selected data with key names as column names.
**For binder**
1. User is able to select tags;
2. User is able to select keys;
