### ISSUE TITLE
Wrong key delimiter in user key column 

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#68]
for user defined column, all keys are combined as one string, which causes issues.
For example, I have keys (key1, key2, key3), which shows in keys column as: key1; key2; key3.
However, when a user searches the key, it uses space (" ") as delimiter instead of ";".
Therefore ";" is treated as part of the key name, which is wrong. It could be simply verified:
1. a user cannot search in order of key3; key2;
2. have to leave space between keys instead of using ";"

**Comment by dongliu** [comment]
The `;` is a delimiter chosen when render the key array. 
what delimiter do you suggest? I can use a space.

**Comment by shengb** [comment]
The `;` is a good choice. The problem is that it is treated as part of key name after rendering.
As above example, when I have `key1; key2; key3`, I cannot search in the syntax for example `key3; key1`

**Comment by dongliu** [comment]
I will then modify the filter context

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/70
