### ISSUE TITLE
Forced validation checking

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#79]
A validation checking is forced for a traveler once it is initialized even before starting to work. 

The field border shows red if not filled yet, like the 1) in picture.

For a radio box, all fields are red before filling. Even after it is filled, the other choices are still in red unless refresh the page as shown in 2) in the picture.

That was introduced after improving the number range checking.
![screen shot 2018-10-08 at 4 22 19 pm](https://user-images.githubusercontent.com/3741779/46634655-23328580-cb17-11e8-8ad7-79a9947c89b5.png)

**Comment by dongliu** [comment]
this is a *feature* implemented together with the out of range number input. I think it is useful for the users to draw attention. If you do not want it, I can turn them off.

**Comment by shengb** [comment]
OK, let's leave it. 
But we do need to address the radio problem like 1) shows. 
When a user input saved, it should not show the rest red anymore.
