### ISSUE TITLE
Number inputs should not allow adding text. 

### ISSUE THREAD

**Issue by iTerminate** [AdvancedPhotonSource/traveler#80]
When a user enters text in a number input 'null' is saved.

**Comment by dongliu** [comment]
reproduced on firefox. 
chrome behaves much better than firefox. It rejects any input that is not a digit.

**Comment by shengb** [comment]
The error message is misleading. The value in error message ("null") does not match user's input ("what") as shown in picture below.

![screen shot 2018-10-12 at 1 16 02 pm](https://user-images.githubusercontent.com/3741779/46886633-14064d00-ce21-11e8-9704-02a9ccbd61e9.png)

**Comment by dongliu** [comment]
fixed in https://github.com/AdvancedPhotonSource/traveler/pull/90
