### ISSUE TITLE
API improvement to reflect table reporting

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#86]
Improve the API to return key-value pair data together with their labels. A JSON example could be like:
{
'title': {'label': 'example1', 'value': 'my value example'},
'status': {'label': 'my status', 'value': 1},
keyvalue:
    {
        'key': {'label': 'my key1', 'value': 'value1'},
        'key2': {'label': 'my key2', 'value': 'value2'},
    }
}

**Comment by dongliu** [comment]
in https://github.com/AdvancedPhotonSource/traveler/pull/98

the endpoint is `https://localhost:3443/apis/travelers/:id/keylabelvalue/`
