### ISSUE TITLE
Adding new key to template results as duplicated key

### ISSUE THREAD

**Issue by shengb** [AdvancedPhotonSource/traveler#9]
When I ran the latest code in docker to create a new template with a user defined key, it reported a duplicated key as shown below.
![screen shot 2018-09-06 at 4 55 52 pm](https://user-images.githubusercontent.com/3741779/45187271-bcf3d380-b1f5-11e8-839a-3ae35c04aced.png)

On another try, I was able to add the same key.

**Comment by dongliu** [comment]
This should be fixed in https://github.com/AdvancedPhotonSource/traveler/pull/12

**Comment by iTerminate** [comment]
Cannot assign a user defined key to a radio button set.

**Comment by shengb** [comment]
Reopen as a new issue dedicated to radio button, and close this one.
